import WeatherPage from "@/components/WeatherPage";
import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import SearchIcon from "@mui/icons-material/Search";
import Spinner from "@/components/Spinner";

const api = {
  key: "855897f0763c1c8f923bb46dee41f61a",
  base: "http://api.openweathermap.org/data/2.5/",
};

export default function Home() {
  const [search, setSearch] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const searchPressed = (e) => {
    setLoading(true);
    fetch(`${api.base}weather?q=${search}&units=metric&APPID=${api.key}`)
      .then((res) => res.json())
      .then((result) => {
        setWeather(result);
      });
    setSearch("");
    setLoading(false);
  };

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div>
        <Head>
          <title>Weather Next-App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className=" absolute top-0 left-0 right-0 bottom-0 z-[1] bg-black/40 " />
        <Image
          src="https://images.pexels.com/photos/1292115/pexels-photo-1292115.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          layout="fill"
          className="object-center"
        />

        <div className=" relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10 ">
          <div className=" flex justify-between items-center w-full m-auto mt-20 p-3 bg-transparent border border-gray-300 text-white rounded-2xl ">
            <div className="">
              <input
                className=" bg-transparent border-none text-white focus:outline-none text-2xl uppercase "
                type="text"
                placeholder="Search city"
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
            <button
              onClick={() => {
                searchPressed();
              }}
            >
              <SearchIcon className="text-[28px] text-gray-300" />
            </button>
          </div>
        </div>
        {weather.main && <WeatherPage data={weather} />}
      </div>
    );
  }
}
